# Generated by Django 6.0.4 on 2026-05-02 11:12

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_coordinators_alter_activity_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'activity')},
        ),
    ]
